spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5435/paymentdb
    username: payment
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

server:
  port: 8084
