spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5434/orderdb
    username: order
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

server:
  port: 8083
